In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
data = pd.read_csv("../input/olympics/14.csv")
data #displaying the content of the file

In [5]:
data.dtypes

In [6]:
data.isnull().sum()

In [7]:
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['Age'] = data['Age'].astype(np.int64) #Age of the players is almost identical
                                           #And the number of void values is really small
data['Height'].fillna(data['Height'].mean(),inplace=True)#Number of void values is really small
data['Weight'].fillna(data['Weight'].mean(),inplace=True)#Number of void values is really small
data.isna().sum()

In [8]:
filt = data['Medal']=='Silver'
data[filt]

In [9]:
pd.unique(data['Age'])

In [10]:
data['Medal']

In [11]:
#Question 2
silver = data[(data['Medal'] == 'Silver')]
val = silver['Age'].value_counts().rename_axis('Silver_age').reset_index(name='No._Of_Medals')
fig=plt.figure()
ax=fig.add_axes([0,0,2,2])
ax.bar(val['Silver_age'],val['No._Of_Medals'],color='b')
ax.set_xlabel('Age of athletes')
ax.set_ylabel('Silver Medals won')
ax.set_title('Silver Medal Distribution')
plt.show()

In [12]:
#Question 3
data['BMI'] = data['Weight']/data['Height']**2

In [13]:
#Question 4
plt.figure(figsize=(30,10))
data.plot.scatter(x="Height",y="Weight")
#From the plot its clear that its positive corelation

In [14]:
#Question 5
last5 = data['Year']>2015
data[last5]

In [15]:
data.groupby(['Sex']).size().plot(kind='pie',y='last5',figsize=(10,10),autopct='%1.1f%%')

In [16]:
#Task questions
#1
maxteam = data['Team'].value_counts()
maxteam

In [17]:
max_year = data.Team.value_counts()
data2 = data.query('Team=="Poland"')
data2.groupby(['Year','Medal']).size().unstack().plot(kind='bar',stacked=True)

In [18]:
data['Sport'].value_counts().to_dict()
data['Sex'].astype(str)
years = [1988,1984,1980,1976,1972]
m=[]
f=[]
for i in years:
    year_grouped = data.loc[data.Year == i]
    male_grouped = year_grouped.loc[year_grouped.Sex == 'M']
    female_grouped = year_grouped.loc[year_grouped.Sex == 'F']
    m.append(male_grouped.size)
    f.append(female_grouped.size)

gender_grouped = pd.DataFrame([[years[x], m[x], f[x]] for x in range(5)],
                  columns=['Year', 'M', 'F'])

gender_grouped.plot(x='Year',
        kind='bar',
        stacked=False,
        title='Gender Distrubution in last 5 years')
plt.ylabel('Count')

In [19]:
k=pd.DataFrame({'Name':data['Name'],'Medal':data['Medal'],'Year':data['Year']})
q=pd.DataFrame({'Name':data['Name'].unique()});
q['Medal Frequency']=0
q['Years participated']=0
count1 =0;
for i in q['Name']:
    count =0
    max=1924
    min=2014
    for j in k['Name']:
        if (j==i):
            q['Medal Frequency'][count1]+=1;
            if (k['Year'][count]>=max):
                max=k['Year'][count]
            if (k['Year'][count]<=min):
                min=k['Year'][count]
        count+=1;
    q['Years participated'][count1]=(max-min)+1;               
    count1+=1;
#GIVEN DATAFRAME HAS ALL DETAILS ABOUT PLAYERS AND THE NUMBER OF MEDALS WON
q

In [20]:
q['Success Rate']= q['Medal Frequency']/q['Years participated']
success=q['Success Rate'].max();
count=0

for i in q['Success Rate']:
    if (i==success):
        print(q['Name'][count], "is the most successful athlete")
    count+=1;